(defpackage #:org.shirakumo.fraf.turbojpeg.cffi
  (:use #:cl)
  (:export
   #:libturbojpeg
   #:init-type
   #:chrominance-sampling
   #:mcu-width
   #:mcu-height
   #:pixel-format
   #:red-offset
   #:green-offset
   #:blue-offset
   #:alpha-offset
   #:pixel-size
   #:color-space
   #:parameter
   #:error-type
   #:operation
   #:option
   #:scaling-factor
   #:scaling-factor-numerator
   #:scaling-factor-denominator
   #:region
   #:region-x
   #:region-y
   #:region-w
   #:region-h
   #:transform
   #:transform-region
   #:transform-operation
   #:transform-options
   #:transform-data
   #:transform-custom-filter
   #:set-parameter
   #:get-parameter
   #:compress
   #:compress/12
   #:compress/16
   #:compress-from-yuv
   #:compress-from-yuv-planes
   #:jpeg-buffer-size
   #:yuv-buffer-size
   #:yuv-plane-size
   #:yuv-plane-width
   #:encode-yuv
   #:encode-yuv-planes
   #:decompress-header
   #:get-scaling-factors
   #:decompress
   #:decompress/12
   #:decompress/16
   #:decompress-to-yuv
   #:decompress-to-yuv-planes
   #:decode-yuv
   #:decode-yuv-planes
   #:transform
   #:destroy
   #:alloc
   #:load-image
   #:load-image/12
   #:load-image/16
   #:save-image
   #:save-image/12
   #:save-image/16
   #:free
   #:error-string
   #:error-code))

(defpackage #:org.shirakumo.fraf.jpeg.cffi
  (:use #:cl)
  (:export
   #:dct-size
   #:dct-size-2
   #:quantization-tables
   #:huffman-tables
   #:arith-coding-tables
   #:max-scan-components
   #:max-sampling-factor
   #:max-blocks-in-mcu
   #:color-space
   #:dct-method
   #:dither-mode
   #:read-header-return
   #:consume-input-return
   #:quantization-table
   #:quantization-table-values
   #:quantization-table-sent-p
   #:huffman-table
   #:huffman-table-bits
   #:huffman-table-values
   #:huffman-table-sent-p
   #:component-info
   #:component-info-component-id
   #:component-info-component-index
   #:component-info-horizontal-sampling-factor
   #:component-info-vertical-sampling-factor
   #:component-info-quantization-table
   #:component-info-dc-entropy-table
   #:component-info-ac-entropy-table
   #:component-info-width-in-blocks
   #:component-info-height-in-blocks
   #:component-info-dct-horizontal-scaled-size
   #:component-info-dct-vertical-scaled-size
   #:component-info-downsampled-width
   #:component-info-downsampled-height
   #:component-info-component-needed-p
   #:component-info-mcu-width
   #:component-info-mcu-height
   #:component-info-mcu-blocks
   #:component-info-mcu-sample-width
   #:component-info-last-column-width
   #:component-info-last-row-height
   #:component-info-quantization-table
   #:component-info-dct-table
   #:scan-info
   #:scan-info-components-in-scan
   #:scan-info-component-index
   #:scan-info-ss
   #:scan-info-se
   #:scan-info-ah
   #:scan-info-al
   #:marker
   #:marker-next
   #:marker-marker
   #:marker-original-length
   #:marker-data-length
   #:marker-data
   #:compressor
   #:compressor-error-manager
   #:compressor-memory-manager
   #:compressor-progress-manager
   #:compressor-client-data
   #:compressor-decompressor-p
   #:compressor-global-state
   #:compressor-destination-manager
   #:compressor-image-width
   #:compressor-image-height
   #:compressor-input-components
   #:compressor-input-color-space
   #:compressor-input-gamma
   #:compressor-scale-number
   #:compressor-scale-denominator
   #:compressor-scaled-width
   #:compressor-scaled-height
   #:compressor-data-precision
   #:compressor-component-count
   #:compressor-color-space
   #:compressor-component-info
   #:compressor-quantization-tables
   #:compressor-q-scale-factor
   #:compressor-dc-tables
   #:compressor-ac-tables
   #:compressor-arith-dc-l
   #:compressor-arith-dc-u
   #:compressor-arith-dc-k
   #:compressor-scan-conut
   #:compressor-scan-info
   #:compressor-raw-data-in
   #:compressor-arith-code
   #:compressor-optimize-coding
   #:compressor-ccir601-sampling
   #:compressor-fancy-downsampling
   #:compressor-smoothing-factor
   #:compressor-dct-method
   #:compressor-restrat-interval
   #:compressor-restart-in-rows
   #:compressor-write-jfif-header
   #:compressor-jfif-major-version
   #:compressor-jfif-minor-version
   #:compressor-density-unit
   #:compressor-x-density
   #:compressor-y-density
   #:compressor-write-adobe-marker
   #:compressor-next-scanline
   #:compressor-progressive-mode
   #:compressor-max-horizontal-sampling-factor
   #:compressor-max-vertical-sampling-factor
   #:compressor-min-dct-horizontal-scaled-size
   #:compressor-min-dct-vertical-scaled-size
   #:compressor-total-imcu-rows
   #:compressor-components-in-scan
   #:compressor-current-component-info
   #:compressor-mcus-per-row
   #:compressor-mcu-rows-in-scan
   #:compressor-blocks-in-mcu
   #:compressor-mcu-membership
   #:compressor-ss
   #:compressor-se
   #:compressor-ah
   #:compressor-al
   #:compressor-block-size
   #:compressor-natural-order
   #:compressor-lim-se
   #:compressor-compression-master
   #:compressor-c-main-controller
   #:compressor-c-prep-controller
   #:compressor-c-coef-controller
   #:compressor-marker-writer
   #:compressor-color-converter
   #:compressor-downsampler
   #:compressor-forward-dct
   #:compressor-entropy-encoder
   #:compressor-script-space
   #:compressor-script-space-size
   #:decompressor
   #:decompressor-error-manager
   #:decompressor-memory-manager
   #:decompressor-progress-manager
   #:decompressor-client-data
   #:decompressor-decompressor-p
   #:decompressor-global-state
   #:decompressor-source-manager
   #:decompressor-image-width
   #:decompressor-image-height
   #:decompressor-components
   #:decompressor-color-space
   #:decompressor-output-color-space
   #:decompressor-scale-number
   #:decompressor-scale-denominator
   #:decompressor-output-gamma
   #:decompressor-buffered-image
   #:decompressor-raw-data-out
   #:decompressor-dct-method
   #:decompressor-fancy-upsampling
   #:decompressor-block-smoothing
   #:decompressor-quantize-colors
   #:decompressor-dither-mode
   #:decompressor-two-pass-quantize
   #:decompressor-enable-1-pass-quantization
   #:decompressor-enable-external-quantization
   #:decompressor-enable-2-pass-quantization
   #:decompressor-output-width
   #:decompressor-output-height
   #:decompressor-output-color-components
   #:decompressor-output-components
   #:decompressor-recommended-outbuffer-height
   #:decompressor-actual-number-of-colors
   #:decompressor-colormap
   #:decompressor-output-scanline
   #:decompressor-input-scan-number
   #:decompressor-input-imcu-row
   #:decompressor-outptu-scan-number
   #:decompressor-output-imcu-row
   #:decompressor-coef-bits
   #:decompressor-quantization-tables
   #:decompressor-dc-huffman-tables
   #:decompressor-ac-huffman-tables
   #:decompressor-data-precision
   #:decompressor-component-info
   #:decompressor-baseline-p
   #:decompressor-progressive-mode
   #:decompressor-arith-code
   #:decompressor-arith-dc-l
   #:decompressor-arith-dc-u
   #:decompressor-arith-dc-k
   #:decompressor-restart-interval
   #:decompressor-saw-jfif-marker
   #:decompressor-jfif-major-version
   #:decompressor-jfif-minor-version
   #:decompressor-density-unit
   #:decompressor-x-density
   #:decompressor-y-density
   #:decompressor-saw-adobe-marker
   #:decompressor-adobe-transform
   #:decompressor-ccir601-sampling
   #:decompressor-marker-list
   #:decompressor-max-horizontal-sampling-factor
   #:decompressor-max-vertical-sampling-factor
   #:decompressor-min-dct-horizontal-scaled-size
   #:decompressor-min-dct-vertical-scaled-size
   #:decompressor-total-imcu-rows
   #:decompressor-sample-range-limit
   #:decompressor-components-in-scan
   #:decompressor-current-component-info
   #:decompressor-mcus-per-row
   #:decompressor-mcu-rows-in-scan
   #:decompressor-blocks-in-mcu
   #:decompressor-mcu-membership
   #:decompressor-ss
   #:decompressor-se
   #:decompressor-ah
   #:decompressor-al
   #:decompressor-block-size
   #:decompressor-natural-order
   #:decompressor-lim-se
   #:decompressor-unread-marker
   #:decompressor-decompression-master
   #:decompressor-d-main-controller
   #:decompressor-d-coef-controller
   #:decompressor-d-post-controller
   #:decompressor-input-controller
   #:decompressor-marker-reader
   #:decompressor-entropy-decoder
   #:decompressor-inverse-dct
   #:decompressor-upsampler
   #:decompressor-color-deconverter
   #:decompressor-color-quantizer
   #:error-manager
   #:error-manager-error-exit
   #:error-manager-emit-message
   #:error-manager-output-message
   #:error-manager-format-message
   #:error-manager-reset-error-manager
   #:error-manager-message-code
   #:error-manager-parameters
   #:error-manager-trace-level
   #:error-manager-warning-count
   #:error-manager-message-table
   #:error-manager-last-message
   #:error-manager-addon-message-table
   #:error-manager-first-addon-message
   #:error-manager-last-addon-message
   #:progress-manager
   #:progress-manager-monitor
   #:progress-manager-pass-counter
   #:progress-manager-pass-limit
   #:progress-manager-completed-passes
   #:progress-manager-total-passes
   #:destination-manager
   #:destination-manager-next-output-byte
   #:destination-manager-free-in-buffer
   #:destination-manager-init-destination
   #:destination-manager-empty-output-buffer
   #:destination-manager-term-destination
   #:source-manager
   #:source-manager-next-input-byte
   #:source-manager-bytes-in-buffer
   #:source-manager-init-source
   #:source-manager-fill-input-buffer
   #:source-manager-skip-input-data
   #:source-manager-resync-to-restart
   #:source-manager-term-source
   #:memory-manager
   #:memory-manager-alloc-small
   #:memory-manager-alloc-large
   #:memory-manager-alloc-sarray
   #:memory-manager-alloc-barray
   #:memory-manager-request-virt-sarray
   #:memory-manager-request-virt-barray
   #:memory-manager-realize-virt-arrays
   #:memory-manager-access-virt-sarray
   #:memory-manager-access-virt-barray
   #:memory-manager-free-pool
   #:memory-manager-self-destruct
   #:memory-manager-max-memory-to-use
   #:memory-manager-max-alloc-chunk
   #:error-manager
   #:make-compress
   #:make-decompress
   #:destroy-compress
   #:destroy-decompress
   #:file-dest
   #:file-src
   #:memory-dest
   #:memory-src
   #:set-defaults
   #:set-color-space
   #:default-color-space
   #:set-quality
   #:set-linear-quality
   #:default-quantization-tables
   #:add-quantization-table
   #:quality-scaling
   #:enable-lossless
   #:simple-progression
   #:suppress-tables
   #:make-quantization-table
   #:make-huffman-table
   #:start-compress
   #:write-scanlines
   #:write-scanlines/12
   #:write-scanlines/16
   #:finish-compress
   #:calculate-jpeg-dimensions
   #:write-raw-data
   #:write-raw-data/12
   #:write-marker
   #:write-m-header
   #:write-m-byte
   #:write-tables
   #:write-icc-profile
   #:read-header
   #:start-decompress
   #:read-scanlines
   #:read-scanlines/12
   #:read-scanlines/16
   #:skip-scanlines
   #:skip-scanlines/16
   #:crop-scanline
   #:crop-scanline/12
   #:finish-decompress
   #:read-raw-data
   #:read-raw-data/12
   #:multiple-scans-p
   #:output-started-p
   #:output-finished-p
   #:input-complete-p
   #:new-colormap
   #:consume-input
   #:core-output-dimensions
   #:calculate-output-dimensions
   #:save-markers
   #:set-marker-processor
   #:read-coefficients
   #:write-coefficients
   #:copy-critical-parameters
   #:abort-compress
   #:abort-decompress
   #:abort
   #:destroy
   #:resync-to-restart
   #:read-icc-profile))

(defpackage #:org.shirakumo.fraf.turbojpeg
  (:use #:cl)
  (:local-nicknames
   (#:turbojpeg #:org.shirakumo.fraf.turbojpeg.cffi))
  (:export))
